apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: cupiemayo/myapp:latest  # <-- This will be replaced
          ports:
            - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  type: LoadBalancer  # or ClusterIP + Ingress
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8080

